HOST: http://api.empregosevagas.com.br/

--- API empregos e vagas V1.0 ---
---
Bem vindo.

A API 1.0 implementa apenas dois métodos nesta fase: Listar vagas e detalhes das vagas.

Com o suporte destas duas ações, uma empresa não precisa se preocupar com o desenvolvimento de uma ferramenta proprietária para listar suas vagas em suas apps/intranets ou websites.

O cadastro e gerenciamento de vagas, deve ser feito através do painel de gestão de empresas (http://empregosevagas.com.br/empresas/painel). Lá existem ferramentas adequadas para a gestão de vagas e seus candidatos, por isso no momento ainda não suportamos o cadastro de vagas via API, mas isto não tem previsão ainda.

---

--
Listar vagas
--
Lista as vagas cadastradas pela empresa, com suporte para status, limites, etc; 
GET /list_positions{status, order, limit, format}
< 200
< Content-Type: application/json
{ "items": [
{ "vaga_id": "0473196F7744EDFB606", "titulo":"2ZY48XPZ", "URL": "vagas/2ZY48XPZ", "vaga_quantidade": 1, "vaga_status": "aberta" }
] }


Save new products in your shopping cart
POST /shopping-cart
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }

